// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIr1PZ-sP3d0wKp6PGBb6p8VTDeLE3moM',
    appId: '1:557802161294:web:98672c030521733ed4f5df',
    messagingSenderId: '557802161294',
    projectId: 'csdl-d9373',
    authDomain: 'csdl-d9373.firebaseapp.com',
    storageBucket: 'csdl-d9373.firebasestorage.app',
    measurementId: 'G-5NSX64QZBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8vZo0340Rx6I52rkJbu1ACIQNabDYkA',
    appId: '1:557802161294:android:17581e7054af862ad4f5df',
    messagingSenderId: '557802161294',
    projectId: 'csdl-d9373',
    storageBucket: 'csdl-d9373.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAactaVqEt3wezYMwBwsVzdQEAyLnPEVvU',
    appId: '1:557802161294:ios:d5f002b0642db4ead4f5df',
    messagingSenderId: '557802161294',
    projectId: 'csdl-d9373',
    storageBucket: 'csdl-d9373.firebasestorage.app',
    iosBundleId: 'com.nhom18.ud-dat-mon-an',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAactaVqEt3wezYMwBwsVzdQEAyLnPEVvU',
    appId: '1:557802161294:ios:81caa8b31083bca5d4f5df',
    messagingSenderId: '557802161294',
    projectId: 'csdl-d9373',
    storageBucket: 'csdl-d9373.firebasestorage.app',
    iosBundleId: 'com.example.ungdungDatMonAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIr1PZ-sP3d0wKp6PGBb6p8VTDeLE3moM',
    appId: '1:557802161294:web:fad82de2be33f715d4f5df',
    messagingSenderId: '557802161294',
    projectId: 'csdl-d9373',
    authDomain: 'csdl-d9373.firebaseapp.com',
    storageBucket: 'csdl-d9373.firebasestorage.app',
    measurementId: 'G-LRVFQQ113M',
  );
}
